spring: 
    http: 
        encoding: 
            force: true
            charset: UTF-8
            enable: true
    datasource:
        url: jdbc:mysql:///market?useUnicode=true&characterEncoding=UTF-8   
        username: root
        password: usbw
        driver-class-name: com.mysql.jdbc.Driver
server: 
    port: 8012
    tomcat:
        uri-encoding: UTF-8